config/routes.rb
MyGist::Application.routes.draw do
  root to: "gists#index"
  resources :gists
  match 'gists-search', to: "gists#search", as: 'searchgist', via: [:get,:post]
  resources :groups, only: [:new, :create, :edit, :update, :destroy]

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/gist.rb
class Gist < ActiveRecord::Base
  belongs_to :group

  validates :snippet,
    presence: true,
    length: { minimum: 3 }

  validates :lang,
    presence: true,
    length: { minimum: 3 }

  validates :description,
    presence: true,
    length: { minimum: 5 }

  validates :group_id,
    presence: true

  self.per_page = 10

  def self.search(search)
    if search
      find(:all, :conditions => ['lang LIKE ?',"%#{search}%"])
    else
      find(:all)
    end
  end	
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :gists

  validates :name,
    presence: true,
    length: { minimum: 1 }
end

app/models/user.rb
class User < ActiveRecord::Base
  
  validates :name,
    presence: true,
    length: { minimum: 1 }
  
  def self.from_omniauth(auth)
    puts auth
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      if auth.provider == "facebook"
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      elsif auth.provider == "github"
        user.provider = auth.provider
        user.uid = auth.uid
        user.name = auth.info.nickname
      end
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_if_logged
    if !current_user
      redirect_to root_path
    end
  end
end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_action :set_gist, only: [:show, :edit, :update, :destroy]
  before_filter :check_if_logged, only: [:edit,:update,:destroy]

  def index
    @gists = Gist.paginate(:page => params[:page]).order('created_at DESC').search(params[:search])
    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
  end

  def new
    @gist = Gist.new
  end

  def create
    @gist = Gist.new(gist_params)
    respond_to do |format|
      if @gist.save
        format.html { redirect_to @gist, notice: 'Gist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gist }
      else
        format.html { render action: 'new' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end


  def update
    respond_to do |format|
      if @gist.update(gist_params)
        format.html { redirect_to @gist, notice: 'Gist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gist.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gist.destroy
    respond_to do |format|
      format.html { redirect_to gists_url }
      format.json { head :no_content }
    end
  end

  def search
    @gists = Gist.search(params[:lang])
  end

  private
    def set_gist
      @gist = Gist.find(params[:id])
    end

    def gist_params
      params.require(:gist).permit(:snippet, :lang, :description, :group_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_filter :check_if_logged
  
  def new
    @groups = Group.order('created_at').paginate(:page => params[:page])
    @group = Group.new
  end

  def create
    @group = Group.new(group_parameters)
    if @group.save
      redirect_to new_group_path, notice: "You successfully created group."
    else
      render action: 'new'
    end
  end

  def edit
    @groups = Group.order('created_at').paginate(:page => params[:page])
    @group = Group.find(params[:id])
  end

  def update
    debugger
    @group = Group.find(params[:id])
    if @group.update_attributes(group_parameters)
      redirect_to :back, notice: "You successfully edited group."
    else
      render action: 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path, notice: "You successfully deleted group."
  end

  private
  def group_parameters
    params.require(:group).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>

      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snippet %><br>
    <%= f.text_area :snippet, :size => "30x10" %>
  </div>
  <div class="field">
    <%= f.label :lang %><br>
    <%= f.text_field :lang, :size => "30x15" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, :size => "30x15" %>
  </div>
  <div class="field">
    <%= f.label :group %><br>
    <%= f.select :group_id, Group.all.collect { |x| [x.name,x.id] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gists/_gist.html.erb
<div class="show_gists">
  <br><br>
  <strong>Snippet:</strong>
  </br></br>  
  <%= raw Pygments.highlight(gist.snippet) %>
  <strong>Lang:</strong>
  <%= gist.lang %>
  </br></br>
  <strong>Description:</strong> 
  <%= gist.description %>
  </br></br>
  <strong>Group:</strong>
  <% if gist.group %>
    <%= gist.group.name %>
  <% else %>
    None
  <% end %>
  </br></br></br>
  <%= link_to 'Show', gist, :class=>"btn btn-info" %>
  <% if current_user %>
  <%= link_to 'Edit', edit_gist_path(gist), :class=>"btn btn-info" %>
  <%= link_to 'Destroy', gist, :class=>"btn btn-info", method: :delete, data: { confirm: 'Are you sure?'} %>
  <% end %>
  </br></br>
</div>
<br><br>

app/views/gists/edit.html.erb
<div class="container-fluid full-width">
<div class="edit_gist">

<%= render 'form' %>

</br></br>

</div>
</div>

app/views/gists/index.html.erb
<div class="container-fluid full-width">

	<div id="my-gists">
    	<%= render @gists %>
	</div>

	<div id="infinite-scrolling">
  		<center><%= will_paginate %></center>
	</div>
</div>

app/views/gists/index.js.erb
$('#my-gists').append('<%= j render @gists %>');
<% if @gists.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @gists %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/gists/new.html.erb
<div class="container-fluid full-width">
<div class="szerokosc">
<div class="new_gist">
     <div class="col-sm-4">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h2>Create your gist</h2>
        </div>
   	 </div>
	</div>

	</br>

	<%= render 'form' %>
		</div>
	</div>
</div>

app/views/gists/search.html.erb
<div class="container-fluid full-width">
<div>
  <div class="style_gist">
    <strong>Lang:</strong>
  </div>

</br>
  
  <%= form_tag gists_path, :method => 'get' do %>       
  <%= (text_field_tag :search, params[:search], class:'form-control') %>
    
    </br>
  
  <div class="szukaj_style">
    <%= submit_tag "Search", class:'btn btn-primary' %>
  </div>
  
  <% end %>
</div>
</div>

   

app/views/gists/show.html.erb
<div class="container-fluid full-width">
	<div class="gists">

		<div class="alert">
			<% if notice %>
    		<p class="alert alert-info"><%= notice %></p>
			<% end %>
		</div>

		<div class="szerokosc">		
			<div class="style_gist">
  			<strong>Snippet:</strong>
				</br></br>
				<%= raw Pygments.highlight(@gist.snippet) %>
			</div>

			<div class="style_gist">
  		  <strong>Lang:</strong>
  		  <%= @gist.lang %>
			</div>

			</br>

			<div class="style_gist">
  			<strong>Description:</strong>
  			<%= @gist.description %>
			</div>

      </br>

      <div class="style_gist">
        <strong>Group:</strong>
        <% if @gist.group %>
          <%= @gist.group.name %>
        <% else %>
          None
        <% end %>
      </div>
      
      </br></br>
      <% if current_user %>
			  <%= link_to 'Edit', edit_gist_path(@gist), :class=>"btn btn-primary" %>
      <% end %>
			</br></br>
		</div>
	</div>
</div>

app/views/groups/_form.html.erb
<div class="groups">
  <div class="container-fluid full-width">
    <div class="col-sm-6">
      <%= render 'index' %>
    </div>
    <div class="col-sm-6">
      <%= form_for @group, 
        url: yield(:url), method: yield(:method) do |f| %>
        <div class="form">
          <div class="field">
            <%= f.label :name %>
            <%= f.text_field :name %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/_index.html.erb
<table>
  <tr>
    <th>Id</th>
    <th>Group Name</th>
  </tr>
  <% for group in @groups %>
    <tr>
      <td><%= group.id %></td>
      <td><%= group.name %></td>
      <td><%= link_to "Edit", edit_group_path(group) %></td>
      <td><%= link_to "Delete", group_path(group), 
        data: { confirm: "Are you sure You want to delete this group?" }, 
        method: :delete %></td>
    </tr>
  <% end %>
</table>

app/views/groups/edit.html.erb
<% provide(:url, group_path(@group)) %>
<% provide(:method, :put) %>
<%= render 'form' %>

app/views/groups/new.html.erb
<% provide(:url, groups_path(@group)) %>
<% provide(:method, :post) %>
<%= render 'form' %>

app/views/layouts/application.html.erb
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">

  <title>MyGist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <div class="col-sm-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">Gists</h2>
      </div>

      <div id="user-widget">
        <% if current_user %>
          Welcome <strong><%= current_user.name %></strong>!
          <%= link_to "Sign out", signout_path, id: "sign_out" %>
        <% else %>
          <%= link_to "Sign in with GitHub", "/auth/github", id: "sign_in" %>
          <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
        <% end %>
      </div>
      <div class="variables">
        <div class="variable1">a</div>
        <div class="variable2">b</div>
        <div class="variable3">c</div>
        <div class="variable4">d</div>
      </div>
      <div class="panel-body">
        <%= link_to "New gist", new_gist_path, class: "list-group-item" %>
        <%= link_to "All gists", gists_path, class: "list-group-item" %>
        <%= link_to "Search gists", searchgist_path, class: "list-group-item" %>
        <% if current_user %>
          <%= link_to "New Group", new_group_path, class: "list-group-item" %>
        <% end %>
      </div>

      <div class="container">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>